### ISSUE TITLE
Amplitude sign wrap 

### ISSUE THREAD

**Issue by dwjbosman** [jorisvr/vhdl_sincos_gen#1]
Hi,

I am using your sine generator in a synthesizer project. The integration has been completed and seems to work. I am seeing some strange behavior in the output of the sine generator. I setup a test bench simulation to investigate as follows:

```
architecture Behavioral of wave_testbench  is
    signal MCLK: std_logic := '0';
    signal resetn: std_logic := '0';
    
    signal iteration: unsigned(19 downto 0);
    signal monitor_sin : signed(23 downto 0);
    signal dummy_cos : signed(23 downto 0);
begin
    Report_Constants(0);

    resetn <= '0', '1' after 100ns;
    MCLK <= not MCLK after 27.1267361111 ns; -- 18.4320 Mhz


    gen0: entity work.sincos_gen
        generic map (
            data_bits       => 24,
            phase_bits      => 20,
            phase_extrabits => 2,
            table_addrbits  => 10,
            taylor_order    => 1 )
        port map (
            clk             => MCLK,
            clk_en          => resetn,
            in_phase        => iteration,
            out_sin         => monitor_sin,
            out_cos         => dummy_cos );

    tst_process : process(MCLK,resetn) is 
    begin
        if resetn = '0' then -- ASynchronous reset (active low)
            iteration <= (others => '0');
        elsif (MCLK'event) and (MCLK = '1') then     
                iteration <= iteration + 1;
        end if;
    end process;

end Behavioral;
```
In vivado 2018.2 I plotted the output:

![screenshot from 2018-09-29 21-06-38](https://user-images.githubusercontent.com/25911924/46249573-c276bf00-c42b-11e8-8dfe-36cf82b2d92a.png)

Which contains glitches when the sine is at peak amplitude.

And here a close up of the first glitch at the positive maximum:

![screenshot from 2018-09-29 21-07-36](https://user-images.githubusercontent.com/25911924/46249587-ce628100-c42b-11e8-8e0f-a9850126c6f1.png)

The 24 bit signed number should has a range of −8,388,608 (0x80000) to 8,388,607 (0x7FFFFF). So the sine output should be max 0x7FFFFF and not 0x800000 (and certainly not 0x800001).

The second glitch occurs at negative maximum. A close up:

![screenshot from 2018-09-29 21-13-19](https://user-images.githubusercontent.com/25911924/46249628-a1fb3480-c42c-11e8-8bd9-030951f3d7b4.png)

The negative maximum should be 0x800000 and not 0x7FFFFF.

Could you help out and try to reproduce this? Thank you for your time and effort.

**Comment by jorisvr** [comment]
Hi Dinne,

You are right, I see the same results when I simulate with your parameters.
I don't know exactly where in the code the overflow occurs, but I think it is basically an accuracy issue: The algorithm is tuned to produce the range -0x7fffff .. +0x7fffff, but inaccuracy in the calculation ("noise" if you will) causes the output to tip into overflow.

The reason for the inaccuracy is your choice of parameters.
There is simply no way to get 24-bit output accuracy with 10-bit tables and 1st order Taylor approximation. To improve accuracy, you would need much bigger tables or 2nd order approximation, and probably also more phase bits.

There are two wrapper entities in the package, one with 20-bit phase, 18-bit output and one with 26-bit phase, 24-bit output. Those two configurations are fully tested and known to be accurate. With any choice of parameters, you are on your own.

Good luck,
Joris.
